openapi: 3.0.3
info:
  title: Payments API
  version: 1.0.0
servers:
- url: /
paths:
  /payments:
    get:
      operationId: listPayments
      parameters:
      - description: "Limit the number of payments to return, pagination can be achieved\
          \ in conjunction with 'skip' parameter."
        example: 10
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: "How many payments to skip, pagination can be achieved in conjunction\
          \ with 'limit' parameter."
        example: 100
        explode: true
        in: query
        name: skip
        required: false
        schema:
          type: integer
        style: form
      - description: Field used to sort payments (Default is by date).
        example: status
        explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPaymentsResponse'
          description: A JSON array of payments
      summary: Returns a list of payments.
      tags:
      - Payments
  /payments/{paymentId}:
    get:
      operationId: getPayment
      parameters:
      - description: The payment id
        example: XXX
        explode: false
        in: path
        name: paymentId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
          description: A payment
      summary: Returns a payment.
      tags:
      - Payments
  /accounts:
    get:
      operationId: listAccounts
      parameters:
      - description: "Limit the number of accounts to return, pagination can be achieved\
          \ in conjunction with 'skip' parameter."
        example: 10
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: "How many accounts to skip, pagination can be achieved in conjunction\
          \ with 'limit' parameter."
        example: 100
        explode: true
        in: query
        name: skip
        required: false
        schema:
          type: integer
        style: form
      - description: Field used to sort payments (Default is by date).
        example: status
        explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAccountsResponse'
          description: A JSON array of accounts
      summary: Returns a list of accounts.
      tags:
      - Payments
  /connectors:
    get:
      description: Get all installed connectors
      operationId: getAllConnectors
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListConnectorsResponse'
          description: List of installed connectors
      summary: Get all installed connectors
      tags:
      - Payments
  /connectors/configs:
    get:
      description: Get all available connectors configs
      operationId: getAllConnectorsConfigs
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListConnectorsConfigsResponse'
          description: List of available connectors configs
      summary: Get all available connectors configs
      tags:
      - Payments
  /connectors/{connector}:
    delete:
      description: Uninstall  connector
      operationId: uninstallConnector
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      responses:
        "204":
          description: Connector has been uninstalled
      summary: Uninstall connector
      tags:
      - Payments
    post:
      description: Install connector
      operationId: installConnector
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectorConfig'
        required: true
      responses:
        "204":
          description: Connector has been installed
      summary: Install connector
      tags:
      - Payments
  /connectors/{connector}/config:
    get:
      description: Read connector config
      operationId: readConnectorConfig
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectorConfig'
          description: Connector config
      summary: Read connector config
      tags:
      - Payments
  /connectors/{connector}/reset:
    post:
      description: Reset connector. Will remove the connector and ALL PAYMENTS generated
        with it.
      operationId: resetConnector
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      responses:
        "204":
          description: Connector has been reset
      summary: Reset connector
      tags:
      - Payments
  /connectors/{connector}/tasks:
    get:
      description: List all tasks associated with this connector.
      operationId: listConnectorTasks
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/listConnectorTasks_200_response_inner'
                type: array
          description: Task list
      summary: List connector tasks
      tags:
      - Payments
  /connectors/{connector}/tasks/{taskId}:
    get:
      description: Get a specific task associated to the connector
      operationId: getConnectorTask
      parameters:
      - description: The connector code
        explode: false
        in: path
        name: connector
        required: true
        schema:
          $ref: '#/components/schemas/Connectors'
        style: simple
      - description: The task id
        example: task1
        explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listConnectorTasks_200_response_inner'
          description: The specified task
      summary: Read a specific task of the connector
      tags:
      - Payments
  /connectors/stripe/transfer:
    post:
      description: Execute a transfer between two Stripe accounts
      operationId: connectorsStripeTransfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeTransferRequest'
        required: true
      responses:
        "200":
          description: Transfer has been executed
      summary: Transfer funds between Stripe accounts
      tags:
      - Payments
components:
  schemas:
    Connectors:
      enum:
      - STRIPE
      - DUMMY-PAY
      - SIE
      - MODULR
      - CURRENCY-CLOUD
      - BANKING-CIRCLE
      type: string
    ConnectorConfig:
      oneOf:
      - $ref: '#/components/schemas/StripeConfig'
      - $ref: '#/components/schemas/DummyPayConfig'
      - $ref: '#/components/schemas/WiseConfig'
      - $ref: '#/components/schemas/ModulrConfig'
      - $ref: '#/components/schemas/CurrencyCloudConfig'
      - $ref: '#/components/schemas/BankingCircleConfig'
    StripeConfig:
      properties:
        pollingPeriod:
          default: 120s
          description: The frequency at which the connector will try to fetch new
            BalanceTransaction objects from Stripe api
          example: 60s
          type: string
        apiKey:
          example: XXX
          type: string
        pageSize:
          default: 10
          description: |
            Number of BalanceTransaction to fetch at each polling interval.
          example: 50
          type: number
      required:
      - apiKey
      type: object
    StripeTask:
      properties:
        oldestId:
          description: The id of the oldest BalanceTransaction fetched from stripe
            for this account
          type: string
        oldestDate:
          description: The creation date of the oldest BalanceTransaction fetched
            from stripe for this account
          format: date-time
          type: string
        moreRecentId:
          description: The id of the more recent BalanceTransaction fetched from stripe
            for this account
          type: string
        moreRecentDate:
          description: The creation date of the more recent BalanceTransaction fetched
            from stripe for this account
          format: date-time
          type: string
        noMoreHistory:
          type: boolean
      type: object
    DummyPayConfig:
      properties:
        filePollingPeriod:
          default: 10s
          description: The frequency at which the connector will try to fetch new
            payment objects from the directory
          example: 60s
          type: string
        fileGenerationPeriod:
          default: 10s
          description: The frequency at which the connector will create new payment
            objects in the directory
          example: 60s
          type: string
        directory:
          example: /tmp/dummypay
          type: string
      required:
      - directory
      type: object
    WiseConfig:
      properties:
        apiKey:
          example: XXX
          type: string
      required:
      - apiKey
      type: object
    ModulrConfig:
      properties:
        apiKey:
          example: XXX
          type: string
        apiSecret:
          example: XXX
          type: string
        endpoint:
          example: XXX
          type: string
      required:
      - apiKey
      - apiSecret
      type: object
    BankingCircleConfig:
      properties:
        username:
          example: XXX
          type: string
        password:
          example: XXX
          type: string
        endpoint:
          example: XXX
          type: string
        authorizationEndpoint:
          example: XXX
          type: string
      required:
      - authorizationEndpoint
      - endpoint
      - password
      - username
      type: object
    CurrencyCloudConfig:
      properties:
        apiKey:
          example: XXX
          type: string
        loginID:
          description: Username of the API Key holder
          example: XXX
          type: string
        pollingPeriod:
          description: The frequency at which the connector will fetch transactions
          example: 60s
          type: string
        endpoint:
          description: The endpoint to use for the API. Defaults to https://devapi.currencycloud.com
          example: XXX
          type: string
      required:
      - apiKey
      - loginID
      type: object
    ListPaymentsResponse:
      example:
        data:
        - reference: reference
          date: 2000-01-23T04:56:07.000+00:00
          amount: 100
          scheme: visa
          provider: provider
          raw: ""
          id: XXX
          type: pay-in
          asset: USD
          status: status
        - reference: reference
          date: 2000-01-23T04:56:07.000+00:00
          amount: 100
          scheme: visa
          provider: provider
          raw: ""
          id: XXX
          type: pay-in
          asset: USD
          status: status
      properties:
        data:
          items:
            $ref: '#/components/schemas/Payment'
          type: array
      required:
      - data
      type: object
    GetPaymentResponse:
      properties:
        data:
          $ref: '#/components/schemas/Payment'
      required:
      - data
      type: object
    Payment:
      example:
        reference: reference
        date: 2000-01-23T04:56:07.000+00:00
        amount: 100
        scheme: visa
        provider: provider
        raw: ""
        id: XXX
        type: pay-in
        asset: USD
        status: status
      properties:
        provider:
          type: string
        reference:
          type: string
        scheme:
          enum:
          - visa
          - mastercard
          - apple pay
          - google pay
          - sepa debit
          - sepa credit
          - sepa
          - a2a
          - ach debit
          - ach
          - rtp
          - other
          type: string
        status:
          type: string
        type:
          enum:
          - pay-in
          - payout
          - other
          type: string
        id:
          example: XXX
          type: string
        amount:
          example: 100
          type: integer
        asset:
          example: USD
          type: string
        date:
          format: date-time
          type: string
        raw:
          nullable: true
      required:
      - amount
      - asset
      - date
      - id
      - provider
      - scheme
      - status
      - type
      type: object
    ListAccountsResponse:
      example:
        data:
        - reference: reference
          createdAt: 2000-01-23T04:56:07.000+00:00
          provider: provider
          id: id
          type: TARGET
        - reference: reference
          createdAt: 2000-01-23T04:56:07.000+00:00
          provider: provider
          id: id
          type: TARGET
      properties:
        data:
          items:
            $ref: '#/components/schemas/Account'
          type: array
      required:
      - data
      type: object
    Account:
      example:
        reference: reference
        createdAt: 2000-01-23T04:56:07.000+00:00
        provider: provider
        id: id
        type: TARGET
      properties:
        id:
          type: string
        createdAt:
          format: date-time
          type: string
        provider:
          type: string
        reference:
          type: string
        type:
          enum:
          - TARGET
          - SOURCE
          type: string
      required:
      - createdAt
      - id
      - provider
      - reference
      - type
      type: object
    ListConnectorsResponse:
      example:
        data:
        - provider: stripe
          disabled: false
        - provider: stripe
          disabled: false
      properties:
        data:
          items:
            $ref: '#/components/schemas/ConnectorBaseInfo'
          type: array
      required:
      - data
      type: object
    ListConnectorsConfigsResponse:
      example:
        connector:
          key:
            datatype: datatype
            required: true
      properties:
        connector:
          $ref: '#/components/schemas/ListConnectorsConfigsResponse_connector'
      type: object
    ConnectorBaseInfo:
      example:
        provider: stripe
        disabled: false
      properties:
        provider:
          example: stripe
          type: string
        disabled:
          example: false
          type: boolean
      type: object
    StripeTransferRequest:
      example:
        amount: 100
        metadata:
          order_id: "6735"
        destination: acct_1Gqj58KZcSIg2N2q
        asset: USD
      properties:
        amount:
          example: 100
          type: integer
        asset:
          example: USD
          type: string
        destination:
          example: acct_1Gqj58KZcSIg2N2q
          type: string
        metadata:
          description: |
            A set of key/value pairs that you can attach to a transfer object.
            It can be useful for storing additional information about the transfer in a structured format.
          example:
            order_id: "6735"
          type: object
      type: object
    TaskDescriptorStripe:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorStripe_descriptor'
      type: object
    TaskDescriptorWise:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorWise_descriptor'
      type: object
    TaskDescriptorModulr:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorModulr_descriptor'
      type: object
    TaskDescriptorDummyPay:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorDummyPay_descriptor'
      type: object
    TaskDescriptorCurrencyCloud:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorCurrencyCloud_descriptor'
      type: object
    TaskDescriptorBankingCircle:
      properties:
        provider:
          description: The connector code
          example: stripe
          type: string
        createdAt:
          description: The date when the task was created
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
        status:
          description: The task status
          enum:
          - stopped
          - pending
          - terminated
          - active
          - failed
          example: stopped
          type: string
        error:
          description: The error message if the task failed
          example: "Error: Something went wrong"
          type: string
        state:
          description: The task state
          example: {}
          type: object
        descriptor:
          $ref: '#/components/schemas/TaskDescriptorBankingCircle_descriptor'
      type: object
    listConnectorTasks_200_response_inner:
      oneOf:
      - $ref: '#/components/schemas/TaskDescriptorStripe'
      - $ref: '#/components/schemas/TaskDescriptorWise'
      - $ref: '#/components/schemas/TaskDescriptorCurrencyCloud'
      - $ref: '#/components/schemas/TaskDescriptorDummyPay'
      - $ref: '#/components/schemas/TaskDescriptorModulr'
      - $ref: '#/components/schemas/TaskDescriptorBankingCircle'
    ListConnectorsConfigsResponse_connector_key:
      example:
        datatype: datatype
        required: true
      properties:
        datatype:
          type: string
        required:
          type: boolean
      type: object
    ListConnectorsConfigsResponse_connector:
      example:
        key:
          datatype: datatype
          required: true
      properties:
        key:
          $ref: '#/components/schemas/ListConnectorsConfigsResponse_connector_key'
      type: object
    TaskDescriptorStripe_descriptor:
      properties:
        name:
          type: string
        main:
          type: boolean
        account:
          type: string
      type: object
    TaskDescriptorWise_descriptor:
      properties:
        name:
          type: string
        key:
          type: string
        profileID:
          type: integer
      type: object
    TaskDescriptorModulr_descriptor:
      properties:
        name:
          type: string
        key:
          type: string
        accountID:
          type: string
      type: object
    TaskDescriptorDummyPay_descriptor:
      properties:
        name:
          type: string
        key:
          type: string
        fileName:
          type: string
      type: object
    TaskDescriptorCurrencyCloud_descriptor:
      properties:
        name:
          type: string
      type: object
    TaskDescriptorBankingCircle_descriptor:
      properties:
        name:
          type: string
        key:
          type: string
      type: object
